---
output:
  md_document:
    variant: markdown_github
---

# Purpose

The aim of this folder is to.... (Explain yourself here)

Load in coding scripts

```{r}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(pacman)
p_load(tidyverse, rmsfuns)

# Source in all your functions:
list.files('code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))

Result <- example_function(x = 10, y = 20)


```


# Data loading

Loading in some really crucial data here, and then producing a beautiful plot:

```{r}

df_flowers <- read_rds('data/flowers.rds')

ggplot(df_flowers) +
    geom_point(aes(Petal.Length, Petal.Width, color = Species) ) +
               labs(title = 'Amazing plot', y = 'petal widths', x = 'petal lengths')

```

# Lastly

* Notice that the 'bin' folder is used for binary files (pdfs, word docs, etc)

* 'settings' folder should be used only for human readable files that are used as user input settings files.

